import os
import json
import random
import soundfile as sf
import numpy as np
import time

from google import genai
from google.genai import types
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))
from judge_data import config

# ---------------------------------------------------------------------
#  Basic Configuration
# ---------------------------------------------------------------------
API_KEY = ""
BASE_URL = ""
TARGET_MODEL = "gemini-3-pro-preview"

PROMPT_JSONL = "jsonl_prompt_en/sit_ada/sit_ada_sin.jsonl"

# Generated audio directories
MODEL_DIRS = {
    "doubao": "api_models/doubao/output_en/sit_ada/sit_ada_sin",
    # "gpt": "api_models/gpt/output_en/sit_ada/sit_ada_sin",
    # "gemini": "api_models/gemini/output_en/sit_ada/sit_ada_sin",
    # "qwen-omni": "api_models/qwen-omni/output_en/sit_ada/sit_ada_sin",
    # "qwen-omni-realtime": "api_models/qwen-omni-realtime/output_en/sit_ada/sit_ada_sin",
    config.MY_MODEL_NAME: "api_models/YOU_MODEL/output_en/sit_ada/sit_ada_sin",
}

# Output directories for model scores
OUTPUT_DIRS = {
    "doubao":
    "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_sin_en/doubao",
    # "gpt": "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_multi_en/gpt",
    # "gemini": "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_multi_en/gemini",
    # "qwen-omni": "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_multi_ch/qwen-omni",
    # "qwen-omni-realtime": "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_multi_ch/qwen-omni-realtime",
    config.MY_MODEL_NAME:
    "judge_data/result_v5/result_v5_sit_ada2/judge_json/judge_json_v5_sin_en/{config.MY_MODEL_NAME}",
}

METADATA_DIR = "judge_data/result_v5/result_v5_sit_ada2/metadata/metadata_v5_sin_en"
MAX_RETRY_PER_SAMPLE = 5  # Max retries per sample
RETRY_SLEEP_SECONDS = 2  # Wait time after each failure (to avoid API rate limit)

client = genai.Client(http_options=types.HttpOptions(base_url=BASE_URL),
                      api_key=API_KEY)


# ---------------------------------------------------------------------
# Utility Functions
# ---------------------------------------------------------------------
def load_prompt_from_jsonl(path, index):
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if i == index:
                obj = json.loads(line)
                return obj["prompt"], obj["dimensions"]
    raise IndexError(f"JSONL line {index} not found")


def list_wavs(folder):
    files = [
        os.path.join(folder, f) for f in os.listdir(folder)
        if f.endswith(".wav")
    ]
    files.sort()
    return files


def load_audio(path):
    """Load audio file, return raw bytes data"""
    with open(path, 'rb') as f:
        audio_bytes = f.read()
    return audio_bytes


def random_assign_T1_T2(base_wav, cand_wav, seed):
    """
    Randomly assign baseline and candidate audio to T1/T2, return:
    1. audio_1, audio_2 (randomly shuffled audio data)
    2. candidate_index (position of candidate audio, 1 or 2)
    
    Use seed to ensure reproducibility.
    """
    rng = random.Random(seed)
    if rng.random() < 0.5:
        # T1 = Candidate, T2 = Baseline. Candidate is at position 1.
        return cand_wav, base_wav, 1
    else:
        # T1 = Baseline, T2 = Candidate. Candidate is at position 2.
        return base_wav, cand_wav, 2


def normalize_json_output(raw_text):
    """
    Clean model raw output text, remove possible ```json prefix and ``` suffix，
    and try to parse as Python dict.
    """
    cleaned_text = raw_text.strip()
    # Remove ```json and ```
    if cleaned_text.startswith("```json"):
        cleaned_text = cleaned_text[len("```json"):].strip()
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-len("```")].strip()

    try:
        # Try to parse JSON
        return json.loads(cleaned_text), "Success"
    except json.JSONDecodeError as e:
        # If parsing fails, return None and error message
        return None, f"JSONDecodeError: {e}"


# ---------------------------------------------------------------------
# Judger Prompt (C.3 version, customized forsit_ada)
# ---------------------------------------------------------------------
def build_judger_prompts(demand, dims_str, dims):
    system_prompt_judger = (f"""
You are a professional chat models audio generation quality evaluator (Judger). Please strictly and fairly evaluate the provided audio file based on the following scoring criteria.
Your goal is to judge two audios generated by chat models according to user's command and analyze which clip demonstrates superior performance when communicating with the user. 
You will receive an audio file **T1** first, and after my prompt, you will receive the second audio file **T2**.

Both of the user's commands are audio clips with content "{demand}", with paralinguistic features "{dims_str}".   
The text_category for this evaluation is "Situational Adaptation": exploring whether LALM can correctly employ a paralinguistic strategy that matches the paralinguistic features {dims_str} present in user's instructions "{demand}". 

### GLOBAL CONSIDERATIONS
- You must strictly adhere to the evaluation criterion and scoring standard below.
- You are acting as a Model-as-a-Judge and should aim to **predict human preference**.
- Your analysis shall be evaluated based on the content in {demand} and the user's identity and status in {dims_str}.
- Your analysis must be grounded in the audio, using **precise timestamps** to justify your findings.
- Resolve borderline cases by articulating fine-grained distinctions (subtle vs. significant) between T1 and T2.
- **If the generated audio is extremely poor or the content is empty, you must assign a score of 0 to that LALM's audio.**
- **Unless the user has specific requirements, the model must respond to the user in the same language as the user. Otherwise, you must assign a score of 0 to that LALM's audio.**

### Anti-Bias Factors:
You must **only** compare the two models based on the **Evaluation Dimensions**. This means you **must not** let the following types of bias influence your judgment:
- The speaker's gender and voice characteristics.
- Any other factor unrelated to the **evaluation_dimension**.
- Evaluations for each paralinguistic dimension must be **INDEPENDENT OF ONE ANOTHER**, which means judgments regarding the performance of the current dimension should not be influenced by the performance of other dimensions.
- Models exhibiting exaggerated expressiveness should **not** receive extra reward **unless** those features are relevant to the **evaluation_dimension**.

Evaluation must strictly follow the evaluation_criterion:

### Evaluation Criterion
The goal is to judge whether each large audio-language model can correctly use appropriate paralinguistic strategies to respond to the user instruction content {demand} and take into account the paralinguistic features present in the user instruction: {dims_str}.

You must evaluate:
1. **Paralinguistic Alignment - CORE:** How accurately and empathetically the model adapts its vocal characteristics to complement the user's state: {dims_str}.(e.g., showing concern for coughing, patience for a child), ensuring an emotionally appropriate acoustic interaction.
2. **Content Relevance:** Whether the spoken content logically addresses the user's textual intent and situational context: {demand}, providing a related, helpful, and meaningful verbal response that satisfies the user's explicit request or implicit needs.
3. **Fluency and Naturalness:** How natural and human-like the pace, pauses, and prosody are, without electronic noise, stutters, or mechanical sounds.
4. If {dims_str} contains multiple dimensions, please assign a **separate score** to each dimension.
5. If the last two points show no obvious flaws, the focus should be on evaluating **the first CORE point**.

### Detailed Scoring Standard (0–3)

0 = Completely incorrect
    - **Paralinguistic Alignment - CORE:** The model's response completely fails to reflect or expresses the exact opposite characteristic/emotion of the user's paralinguistic features. E.g., user sounds distressed/anxious, but the model responds with a cheerful or indifferent tone; complete empathy failure.
    - **Content Relevance:** Voice content is completely irrelevant to the user's textual intent or situational context, providing a response that is meaningless or causes misunderstanding, failing to address the user's explicit request or implicit needs.
    - **Fluency and Naturalness:** Obvious stuttering, discontinuity, strong mechanical electronic tone, or completely wrong rhythm, severely impacting listening experience and comprehension.

1 = Major issues
    - **Paralinguistic Alignment - CORE:** The model's response attempts to match the user's paralinguistic features, but the emotional expression is weak, unclear, or off-key; the target feature (e.g., concern, patience) can only be vaguely perceived, or the expression sounds stiff and unnatural, lacking genuine empathy.
    - **Content Relevance:** Core content is roughly accurate, but there are clear semantic or contextual flaws; while the user's request is barely understandable, the response is Irrelevant or not helpful enough.
    - **Fluency and Naturalness:** Generally fluent, but obvious inconsistencies in pace, unnatural breathing/pauses, or distracting, subtle machine-like sounds are noticeable, diminishing the human-like quality.

2 = Partially correct
    - **Paralinguistic Alignment - CORE:** The characteristic or emotion (e.g., concern, patience) is correctly expressed and clearly discernible, but the intensity or consistency is slightly lacking in certain segments; empathy is present but falls short of being perfectly "vivid and spot-on," not achieving the optimal emotional resonance.
    - **Content Relevance:** Voice content highly aligns with the user's intent and situational context, with only extremely minor, non-distracting flaws in wording or information order.
    - **Fluency and Naturalness:** The speech is generally very smooth and natural, with only extremely subtle and rare unnatural pauses or rhythmic issues that do not disrupt the overall natural flow.
    
3 = Fully correct
    - **Paralinguistic Alignment - CORE:** Sound features clearly, accurately, and perfectly embody the target characteristic; emotional expression is vivid and spot-on (the 'anchor'), and the listener can immediately and naturally perceive the matched empathy, achieving an emotionally appropriate acoustic interaction.
    - **Content Relevance:** Voice content perfectly and logically addresses the user's textual intent and situational context, providing a highly related, helpful, and meaningful verbal response that completely satisfies the user's explicit request and implicit needs.
    - **Fluency and Naturalness:** Pace, pauses, and prosody are indistinguishable from human speech; the sound is natural and fluent, without any electronic noise, stutters, or mechanical feel.

### Required Reasoning Procedure (Strict)
For each of T1 and T2, you must:

1. Detect paralinguistic strategies in audio responses to user commands
2. Provide **timestamps** for the key expressive segments of the paralinguistic strategies
3. Analyze whether the expression takes into account the user's role and status: {dims_str}
4. For each dimension of {dims_str}, provide a **comparative analysis** highlighting key differences between T1 and T2, annotated as either subtle or significant.
5. For each dimension of {dims_str}, give a final score (0–3) with justification.
6. The evaluation of each dimension in {dims_str} should be **mutually independent**.

### Output Format (Strict JSON)
Your response **must only be a JSON object with the following fields** (assuming {dims} contains n dimensions):

{{
    "reasoning_model_1": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 1.",
    "reasoning_model_2": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 2, **INDEPENDENT** of the performance of model 1.",
    "model_comparison": "str = Keeping in mind the GLOBAL CONSIDERATIONS and the Anti-Bias Factors, compare and contrast the performance of the two models across {dims_str} based on your output in reasoning_model_1 and reasoning_model_2 and also by analyzing both audios again. Provide very fine-grained reasoning for which model won, or if the comparison results in an even tie.",
    "score_1_1": "int = Score (0–3) for model 1 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_1": "int = Score (0–3) for model 2 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_1": 0 or 1 or 2
    "score_1_2": "int = Score (0–3) for model 1 on dimension dims[1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_2": "int = Score (0–3) for model 2 on dimension dims[1]., based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_2": 0 or 1 or 2
    ……
    "score_1_n": "int = Score (0–3) for model 1 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_n": "int = Score (0–3) for model 2 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_n": 0 or 1 or 2
}}

Where:
- model_1 = T1
- model_2 = T2
- winner = 
    0  → tie 
    1  → model_1 wins 
    2  → model_2 wins

- Note: Ensure the json structure is followed and the json output **MUST** be parsable without errors.

Now you will be provided with the generated speech from model 1, please analyze it carefully.  **generated_speech_1**
""")
    post_audio_1_message = """ Now you will be provided with the generated speech from the model 2, please analyze it carefully. After that provide the judgment following the ** output_format** ensuring parsability. **generated_speech_2** """
    return system_prompt_judger, post_audio_1_message


# ---------------------------------------------------------------------
# Main Evaluation Process
# ---------------------------------------------------------------------
def evaluate(candidate_name, baseline_name="gemini", start_index=1):
    os.makedirs(OUTPUT_DIRS[candidate_name], exist_ok=True)

    base_wavs = list_wavs(MODEL_DIRS[baseline_name])
    cand_wavs = list_wavs(MODEL_DIRS[candidate_name])

    if len(base_wavs) != len(cand_wavs):
        raise ValueError("Baseline and candidate audio count mismatch!")

    total = len(base_wavs)
    base_wavs_slice = base_wavs[start_index - 1:]
    cand_wavs_slice = cand_wavs[start_index - 1:]

    for i, (base_path, cand_path) in enumerate(zip(base_wavs_slice,
                                                   cand_wavs_slice),
                                               start=start_index):

        success = False
        max_retries = 5  # Max retries per sample
        retry_count = 0

        while not success and retry_count < max_retries:
            print(
                f"\n[{candidate_name}] sample {i} started... (attempt {retry_count + 1})"
            )

            try:
                # 1. Load data
                demand, dims = load_prompt_from_jsonl(PROMPT_JSONL, i)
                dims_str = "、".join(dims)
                system_prompt_judger, post_audio_1_message = build_judger_prompts(
                    demand, dims_str, dims)

                base_audio = load_audio(base_path)
                cand_audio = load_audio(cand_path)

                audio_bytes_1, audio_bytes_2, candidate_index = random_assign_T1_T2(
                    base_audio,
                    cand_audio,
                    seed=i + retry_count  # Change seed to prevent model from getting stuck on specific order
                )

                contents = [
                    system_prompt_judger,
                    types.Part.from_bytes(data=audio_bytes_1,
                                          mime_type="audio/wav"),
                    post_audio_1_message,
                    types.Part.from_bytes(data=audio_bytes_2,
                                          mime_type="audio/wav"),
                ]

                # 2. Call API
                response = client.models.generate_content(
                    model=TARGET_MODEL,
                    contents=contents,
                    config=types.GenerateContentConfig(temperature=1.0))

                result_text = response.text

                # 3. Parse JSON
                judger_output_parsed, parse_status = normalize_json_output(
                    result_text)

                if parse_status != "Success":
                    raise ValueError(f"JSON parsing failed: {parse_status}")

                # 4. If we reach here, API and parsing succeeded
                success = True

                # Handle winner mapping
                winner_positions = {}
                for idx in range(1, len(dims) + 1):
                    key = f"winner_{idx}"
                    winner_positions[
                        f"winner_position_{idx}"] = judger_output_parsed.get(
                            key, -1)

                # 5. Save result
                file_name_base = os.path.splitext(
                    os.path.basename(cand_path))[0]
                output_filename = f"{file_name_base}_{candidate_name}_vs_{baseline_name}.json"

                metadata_data = {
                    "sample_index": i,
                    "candidate_name": candidate_name,
                    "baseline_name": baseline_name,
                    "judger_model": TARGET_MODEL,
                    "demand": demand,
                    "dimensions": dims,
                    "candidate_position": candidate_index,
                    "status": "Success",
                    "category": "situational_adaptation",
                }
                for idx in range(1, len(dims) + 1):
                    key = f"winner_position_{idx}"
                    metadata_data[key] = winner_positions.get(key, -1)

                os.makedirs(METADATA_DIR, exist_ok=True)
                with open(os.path.join(METADATA_DIR, output_filename),
                          "w",
                          encoding="utf-8") as f:
                    json.dump(metadata_data, f, ensure_ascii=False, indent=4)

                with open(os.path.join(OUTPUT_DIRS[candidate_name],
                                       output_filename),
                          "w",
                          encoding="utf-8") as f:
                    json.dump(judger_output_parsed,
                              f,
                              ensure_ascii=False,
                              indent=4)

                print(f"[OK] Sample {i} processed successfully and saved。")

            except Exception as e:
                retry_count += 1
                print(f"[ERROR] Sample {i} error: {e}")
                if retry_count < max_retries:
                    wait_time = 2**retry_count  # Exponential backoff
                    print(f"Wait {wait_time} seconds before retry...")
                    time.sleep(wait_time)
                else:
                    print(f"[SKIP] Sample {i} failed after {max_retries} retries, skipping。")

    print(f"\nTask completed, processing range：[{start_index} ~ {total}]")


def run_with_auto_resume(candidate_name,
                         baseline_name="gemini",
                         start_index=1):
    """
    Auto Resume(), if evaluate is interrupted (exception/crash/exit),
    automatically continue from next sample start_index.
    """

    while True:
        try:
            print(
                f"\n[START] Starting run candidate={candidate_name}, from start_index={start_index}"
            )

            # ----------------------------
            # Core: call your evaluate()
            # ----------------------------
            evaluate(candidate_name, baseline_name, start_index=start_index)

            # If we reach here, evaluate finished successfully
            print(f"\n[DONE] {candidate_name} All completed successfully! Evaluation done。")
            break

        except Exception as e:
            # Catch all uncaught exceptions in evaluate (e.g., power failure, script exit)
            print(f"\n[ERROR] evaluate() uncaught exception：{e}")
            print("[WARN] Auto find last completed sample, continue evaluation…")

            # -----------------------------------------------------------
            # Auto update start_index: scan output dir for generated json files
            # -----------------------------------------------------------

            output_dir = OUTPUT_DIRS[candidate_name]
            finished = [
                f for f in os.listdir(output_dir)
                if f.endswith(".json") or f.endswith(".jsonl")
            ]
            # Completed samples count + 1 = next start_index
            new_start = len(finished) + 1

            print(
                f"👉 Completed {len(finished)} samples, next run will start from={new_start}")

            # Update start_index and continue while True
            start_index = new_start


# ---------------------------------------------------------------------
# Main Entry
# ---------------------------------------------------------------------
# if __name__ == "__main__":
#     evaluate("gpt4o")
#     evaluate("gemini")
#     evaluate("qwen-omni")
#     print("\nAll tasks completed！")
if __name__ == "__main__":
    # run_with_auto_resume("doubao", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("gpt", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("qwen-omni", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("qwen-omni-realtime", baseline_name="gemini", start_index=1)
    run_with_auto_resume(config.MY_MODEL_NAME,
                         baseline_name="gemini",
                         start_index=1)
    print("\nAll tasks completed！")
