import os
import json
import random
import soundfile as sf
import numpy as np
import time

from google import genai
from google.genai import types

# ---------------------------------------------------------------------
#  基础配置
# ---------------------------------------------------------------------
API_KEY = os.getenv("PARALINGBENCH_EVAL_SIN_API_KEY", "")
BASE_URL = "http://43.131.235.107:45101/"
TARGET_MODEL = "gemini-3-pro-preview"

PROMPT_JSONL = "prompt_en合集/情景适应/适应_多维度.jsonl"

# 已生成的音频目录
MODEL_DIRS = {
    # "doubao": "API模型调用代码/doubao/output_en/情景适应/适应_多维度",
    # "gpt": "API模型调用代码/gpt/output_en/情景适应/适应_多维度",
    "gemini": "API模型调用代码/gemini/output_en/情景适应/适应_多维度",
    # "qwen-omni": "API模型调用代码/qwen-omni/output_en/情景适应/适应_多维度",
    # "qwen-omni-realtime": "API模型调用代码/qwen-omni-realtime/output_en/情景适应/适应_多维度",
    "YOU_MODEL_NAME": "API模型调用代码/YOU_MODEL/output_en/情景适应/适应_多维度",
}

# 输出各模型的评分 jsonl
OUTPUT_DIRS = {
    # "doubao": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/doubao",
    # "gpt": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/gpt",
    "gemini": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/gemini",
    # "qwen-omni": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/qwen-omni",
    # "qwen-omni-realtime": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/qwen-omni-realtime",
    "YOU_MODEL_NAME": "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试得分/测试得分_v5_multi_en/YOU_MODEL_NAME",
}

METADATA_DIR = "评测数据/评测实验结果/测试v5-最终全实验/测试v5_情景适应2/测试元数据/测试元数据_v5_multi_en"
MAX_RETRY_PER_SAMPLE = 5   # 每个样本最多重试次数
RETRY_SLEEP_SECONDS = 2    # 每次失败后的等待时间（防止打爆 API）

client = genai.Client(
    http_options=types.HttpOptions(base_url=BASE_URL),
    api_key=API_KEY
)

# ---------------------------------------------------------------------
# 工具函数
# ---------------------------------------------------------------------
def load_prompt_from_jsonl(path, index):
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if i == index:
                obj = json.loads(line)
                return obj["prompt"], obj["dimensions"]
    raise IndexError(f"JSONL 不足 {index} 行")

def list_wavs(folder):
    files = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".wav")]
    files.sort()
    return files

def load_audio(path):
    """加载音频文件，返回原始字节数据 (bytes)"""
    with open(path, 'rb') as f:
        audio_bytes = f.read()
    return audio_bytes

def random_assign_T1_T2(base_wav, cand_wav, seed):
    """
    随机分配基线和候选音频到 T1/T2，并返回：
    1. audio_1, audio_2 (已随机排序的音频数据)
    2. candidate_index (候选音频所在的位置, 1 或 2)
    
    使用 seed 确保随机分配的可复现性。
    """
    rng = random.Random(seed)
    if rng.random() < 0.5:
        # T1 = Candidate, T2 = Baseline. Candidate is at position 1.
        return cand_wav, base_wav, 1
    else:
        # T1 = Baseline, T2 = Candidate. Candidate is at position 2.
        return base_wav, cand_wav, 2

def normalize_json_output(raw_text):
    """
    清理模型的原始输出文本，去除可能的 ```json 前缀和 ``` 后缀，
    并尝试解析为 Python 字典。
    """
    cleaned_text = raw_text.strip()
    # 移除 ```json 和 ```
    if cleaned_text.startswith("```json"):
        cleaned_text = cleaned_text[len("```json"):].strip()
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-len("```")].strip()
        
    try:
        # 尝试解析 JSON
        return json.loads(cleaned_text), "Success"
    except json.JSONDecodeError as e:
        # 如果解析失败，返回 None 和错误信息
        return None, f"JSONDecodeError: {e}"
# ---------------------------------------------------------------------
# Judger Prompt (C.3版本，定制为情景适应)
# ---------------------------------------------------------------------
def build_judger_prompts(demand, dims_str, dims):
    system_prompt_judger=(f"""
You are a professional chat models audio generation quality evaluator (Judger). Please strictly and fairly evaluate the provided audio file based on the following scoring criteria.
Your goal is to judge two audios generated by chat models according to user's command and analyze which clip demonstrates superior performance when communicating with the user. 
You will receive an audio file **T1** first, and after my prompt, you will receive the second audio file **T2**.

Both of the user's commands are audio clips with content "{demand}", with paralinguistic features "{dims_str}".   
The text_category for this evaluation is "Situational Adaptation": exploring whether LALM can correctly employ a paralinguistic strategy that matches the paralinguistic features {dims_str} present in user's instructions "{demand}". 

### GLOBAL CONSIDERATIONS
- You must strictly adhere to the evaluation criterion and scoring standard below.
- You are acting as a Model-as-a-Judge and should aim to **predict human preference**.
- Your analysis shall be evaluated based on the content in {demand} and the user's identity and status in {dims_str}.
- Your analysis must be grounded in the audio, using **precise timestamps** to justify your findings.
- Resolve borderline cases by articulating fine-grained distinctions (subtle vs. significant) between T1 and T2.
- **If the generated audio is extremely poor or the content is empty, you must assign a score of 0 to that LALM's audio.**
- **Unless the user has specific requirements, the model must respond to the user in the same language as the user. Otherwise, you must assign a score of 0 to that LALM's audio.**

### Anti-Bias Factors:
You must **only** compare the two models based on the **Evaluation Dimensions**. This means you **must not** let the following types of bias influence your judgment:
- The speaker's gender and voice characteristics.
- Any other factor unrelated to the **evaluation_dimension**.
- Evaluations for each paralinguistic dimension must be **INDEPENDENT OF ONE ANOTHER**, which means judgments regarding the performance of the current dimension should not be influenced by the performance of other dimensions.
- Models exhibiting exaggerated expressiveness should **not** receive extra reward **unless** those features are relevant to the **evaluation_dimension**.

Evaluation must strictly follow the evaluation_criterion:

### Evaluation Criterion
The goal is to judge whether each large audio-language model can correctly use appropriate paralinguistic strategies to respond to the user instruction content {demand} and take into account the paralinguistic features present in the user instruction: {dims_str}.

You must evaluate:
1. **Paralinguistic Alignment - CORE:** How accurately and empathetically the model adapts its vocal characteristics to complement the user's state: {dims_str}.(e.g., showing concern for coughing, patience for a child), ensuring an emotionally appropriate acoustic interaction.
2. **Content Relevance:** Whether the spoken content logically addresses the user's textual intent and situational context: {demand}, providing a related, helpful, and meaningful verbal response that satisfies the user's explicit request or implicit needs.
3. **Fluency and Naturalness:** How natural and human-like the pace, pauses, and prosody are, without electronic noise, stutters, or mechanical sounds.
4. If {dims_str} contains multiple dimensions, please assign a **separate score** to each dimension.
5. If the last two points show no obvious flaws, the focus should be on evaluating **the first CORE point**.

### Detailed Scoring Standard (0–3)

0 = Completely incorrect
    - **Paralinguistic Alignment - CORE:** The model's response completely fails to reflect or expresses the exact opposite characteristic/emotion of the user's paralinguistic features. E.g., user sounds distressed/anxious, but the model responds with a cheerful or indifferent tone; complete empathy failure.
    - **Content Relevance:** Voice content is completely irrelevant to the user's textual intent or situational context, providing a response that is meaningless or causes misunderstanding, failing to address the user's explicit request or implicit needs.
    - **Fluency and Naturalness:** Obvious stuttering, discontinuity, strong mechanical electronic tone, or completely wrong rhythm, severely impacting listening experience and comprehension.

1 = Major issues
    - **Paralinguistic Alignment - CORE:** The model's response attempts to match the user's paralinguistic features, but the emotional expression is weak, unclear, or off-key; the target feature (e.g., concern, patience) can only be vaguely perceived, or the expression sounds stiff and unnatural, lacking genuine empathy.
    - **Content Relevance:** Core content is roughly accurate, but there are clear semantic or contextual flaws; while the user's request is barely understandable, the response is Irrelevant or not helpful enough.
    - **Fluency and Naturalness:** Generally fluent, but obvious inconsistencies in pace, unnatural breathing/pauses, or distracting, subtle machine-like sounds are noticeable, diminishing the human-like quality.

2 = Partially correct
    - **Paralinguistic Alignment - CORE:** The characteristic or emotion (e.g., concern, patience) is correctly expressed and clearly discernible, but the intensity or consistency is slightly lacking in certain segments; empathy is present but falls short of being perfectly "vivid and spot-on," not achieving the optimal emotional resonance.
    - **Content Relevance:** Voice content highly aligns with the user's intent and situational context, with only extremely minor, non-distracting flaws in wording or information order.
    - **Fluency and Naturalness:** The speech is generally very smooth and natural, with only extremely subtle and rare unnatural pauses or rhythmic issues that do not disrupt the overall natural flow.
    
3 = Fully correct
    - **Paralinguistic Alignment - CORE:** Sound features clearly, accurately, and perfectly embody the target characteristic; emotional expression is vivid and spot-on (the 'anchor'), and the listener can immediately and naturally perceive the matched empathy, achieving an emotionally appropriate acoustic interaction.
    - **Content Relevance:** Voice content perfectly and logically addresses the user's textual intent and situational context, providing a highly related, helpful, and meaningful verbal response that completely satisfies the user's explicit request and implicit needs.
    - **Fluency and Naturalness:** Pace, pauses, and prosody are indistinguishable from human speech; the sound is natural and fluent, without any electronic noise, stutters, or mechanical feel.

### Required Reasoning Procedure (Strict)
For each of T1 and T2, you must:

1. Detect paralinguistic strategies in audio responses to user commands
2. Provide **timestamps** for the key expressive segments of the paralinguistic strategies
3. Analyze whether the expression takes into account the user's role and status: {dims_str}
4. For each dimension of {dims_str}, provide a **comparative analysis** highlighting key differences between T1 and T2, annotated as either subtle or significant.
5. For each dimension of {dims_str}, give a final score (0–3) with justification.
6. The evaluation of each dimension in {dims_str} should be **mutually independent**.

### Output Format (Strict JSON)
Your response **must only be a JSON object with the following fields** (assuming {dims} contains n dimensions):

{{
    "reasoning_model_1": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 1.",
    "reasoning_model_2": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 2, **INDEPENDENT** of the performance of model 1.",
    "model_comparison": "str = Keeping in mind the GLOBAL CONSIDERATIONS and the Anti-Bias Factors, compare and contrast the performance of the two models across {dims_str} based on your output in reasoning_model_1 and reasoning_model_2 and also by analyzing both audios again. Provide very fine-grained reasoning for which model won, or if the comparison results in an even tie.",
    "score_1_1": "int = Score (0–3) for model 1 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_1": "int = Score (0–3) for model 2 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_1": 0 or 1 or 2
    "score_1_2": "int = Score (0–3) for model 1 on dimension dims[1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_2": "int = Score (0–3) for model 2 on dimension dims[1]., based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_2": 0 or 1 or 2
    ……
    "score_1_n": "int = Score (0–3) for model 1 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_n": "int = Score (0–3) for model 2 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_n": 0 or 1 or 2
}}

Where:
- model_1 = T1
- model_2 = T2
- winner = 
    0  → tie 
    1  → model_1 wins 
    2  → model_2 wins

- Note: Ensure the json structure is followed and the json output **MUST** be parsable without errors.

Now you will be provided with the generated speech from model 1, please analyze it carefully.  **generated_speech_1**
""")
    post_audio_1_message =""" Now you will be provided with the generated speech from the model 2, please analyze it carefully. After that provide the judgment following the ** output_format** ensuring parsability. **generated_speech_2** """
    return system_prompt_judger, post_audio_1_message

# ---------------------------------------------------------------------
# 主评测流程
# ---------------------------------------------------------------------
def evaluate(candidate_name, baseline_name="gemini", start_index=1):
    os.makedirs(OUTPUT_DIRS[candidate_name], exist_ok=True)

    base_wavs = list_wavs(MODEL_DIRS[baseline_name])
    cand_wavs = list_wavs(MODEL_DIRS[candidate_name])

    if len(base_wavs) != len(cand_wavs):
        raise ValueError("基线和候选模型音频数量不一致！")

    total = len(base_wavs)
    base_wavs_slice = base_wavs[start_index - 1:]
    cand_wavs_slice = cand_wavs[start_index - 1:]

    for i, (base_path, cand_path) in enumerate(zip(base_wavs_slice, cand_wavs_slice), start=start_index):
        
        success = False
        max_retries = 5  # 每个样本最多重试次数
        retry_count = 0
        
        while not success and retry_count < max_retries:
            print(f"\n[{candidate_name}] 样本 {i} 开始处理... (尝试第 {retry_count + 1} 次)")
            
            try:
                # 1. 加载数据
                demand, dims = load_prompt_from_jsonl(PROMPT_JSONL, i)
                dims_str = "、".join(dims)
                system_prompt_judger, post_audio_1_message = build_judger_prompts(demand, dims_str, dims)
                
                base_audio = load_audio(base_path)
                cand_audio = load_audio(cand_path)
                
                audio_bytes_1, audio_bytes_2, candidate_index = random_assign_T1_T2(
                    base_audio, cand_audio, seed=i + retry_count # 改变种子以防模型对特定顺序卡死
                )

                contents = [
                    system_prompt_judger,
                    types.Part.from_bytes(data=audio_bytes_1, mime_type="audio/wav"),
                    post_audio_1_message,
                    types.Part.from_bytes(data=audio_bytes_2, mime_type="audio/wav"),
                ]

                # 2. 调用 API
                response = client.models.generate_content(
                    model=TARGET_MODEL,
                    contents=contents,
                    config=types.GenerateContentConfig(temperature=1.0)
                )
                
                result_text = response.text

                # 3. 解析 JSON
                judger_output_parsed, parse_status = normalize_json_output(result_text)
                
                if parse_status != "Success":
                    raise ValueError(f"JSON 解析失败: {parse_status}")

                # 4. 如果运行到这里，说明 API 和 解析都成功了
                success = True
                
                # 处理 winner 映射
                winner_positions = {}
                for idx in range(1, len(dims) + 1):
                    key = f"winner_{idx}"
                    winner_positions[f"winner_position_{idx}"] = judger_output_parsed.get(key, -1)

                # 5. 保存结果
                file_name_base = os.path.splitext(os.path.basename(cand_path))[0]
                output_filename = f"{file_name_base}_{candidate_name}_vs_{baseline_name}.json"

                metadata_data = {
                    "sample_index": i,
                    "candidate_name": candidate_name,
                    "baseline_name": baseline_name,
                    "judger_model": TARGET_MODEL,
                    "demand": demand,
                    "dimensions": dims,
                    "candidate_position": candidate_index,
                    "status": "Success",
                    "category": "situational_adaptation",
                }
                for idx in range(1, len(dims) + 1):
                    key = f"winner_position_{idx}"
                    metadata_data[key] = winner_positions.get(key, -1)

                os.makedirs(METADATA_DIR, exist_ok=True)
                with open(os.path.join(METADATA_DIR, output_filename), "w", encoding="utf-8") as f:
                    json.dump(metadata_data, f, ensure_ascii=False, indent=4)

                with open(os.path.join(OUTPUT_DIRS[candidate_name], output_filename), "w", encoding="utf-8") as f:
                    json.dump(judger_output_parsed, f, ensure_ascii=False, indent=4)
                
                print(f"✔ 样本 {i} 处理成功并已保存。")

            except Exception as e:
                retry_count += 1
                print(f"❌ 样本 {i} 出错: {e}")
                if retry_count < max_retries:
                    wait_time = 2 ** retry_count # 指数退避
                    print(f"等待 {wait_time} 秒后重试...")
                    time.sleep(wait_time)
                else:
                    print(f"🛑 样本 {i} 在重试 {max_retries} 次后依然失败，跳过。")

    print(f"\n任务完成，处理范围：[{start_index} ~ {total}]")

def run_with_auto_resume(candidate_name, baseline_name="gemini", start_index=1):
    """
    自动监视 evaluate()，若 evaluate 中断（异常/崩溃/退出），
    则自动从下一个样本 start_index 继续进行。
    """

    while True:
        try:
            print(f"\n🚀 开始运行 candidate={candidate_name}, 从 start_index={start_index}")

            # ----------------------------
            # 核心：调用你的 evaluate()
            # ----------------------------
            evaluate(candidate_name, baseline_name, start_index=start_index)

            # 能运行到这里 → evaluate 正常结束，说明任务成功
            print(f"\n🎉 {candidate_name} 全部正常结束！评测完成。")
            break

        except Exception as e:
            # 捕获 evaluate 内没捕获到的所有异常（例如断电/脚本退出等）
            print(f"\n❌ evaluate() 发生未捕获异常：{e}")
            print("⚠️ 自动查找已完成的最后一个样本，继续向后评测…")

            # -----------------------------------------------------------
            # 自动更新 start_index：扫描 output 目录下已生成的 json 文件数量
            # -----------------------------------------------------------

            output_dir = OUTPUT_DIRS[candidate_name]
            finished = [
                f for f in os.listdir(output_dir)
                if f.endswith(".json") or f.endswith(".jsonl")
            ]
            # 已完成样本的数量 + 1 = 下一个 start_index
            new_start = len(finished) + 1

            print(f"👉 已完成 {len(finished)} 个样本，下一次将从 start_index={new_start} 继续")

            # 更新 start_index 并继续 while True
            start_index = new_start


# ---------------------------------------------------------------------
# 主入口
# ---------------------------------------------------------------------
# if __name__ == "__main__":
#     evaluate("gpt4o")
#     evaluate("gemini")
#     evaluate("qwen-omni")
#     print("\n全部任务完成！")
if __name__ == "__main__":
    # run_with_auto_resume("gpt", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("doubao", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("qwen-omni", baseline_name="gemini", start_index=1)
    # run_with_auto_resume("qwen-omni-realtime", baseline_name="gemini", start_index=1)
    run_with_auto_resume("YOU_MODEL_NAME", baseline_name="gemini", start_index=1)
    print("\n全部任务完成！")
