import os
import json
import random
import soundfile as sf
import numpy as np
import time

from google import genai
from google.genai import types

import sys
import os

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))
from judge_data import config

# ---------------------------------------------------------------------
#  Basic Configuration
# ---------------------------------------------------------------------
API_KEY = config.API_KEY
BASE_URL = config.BASE_URL
TARGET_MODEL = "gemini-3-pro-preview"

PROMPT_JSONL = "jsonl_prompt_ch/dyn_var/dyn_var.jsonl"

# Generated audio directories
MODEL_DIRS = {
    "doubao": "api_models/doubao/output_ch/dyn_var",
    config.MY_MODEL_NAME:
    f"api_models/{config.MY_MODEL_NAME}/output_ch/dyn_var",
    # "gpt": "api_models/gpt/output_ch/dyn_var",
    # "gemini": "api_models/gemini/output_ch/dyn_var",
    # "qwen-omni": "api_models/qwen-omni/output_ch/dyn_var",
    # "qwen-omni-realtime": "api_models/qwen-omni-realtime/output_ch/dyn_var",
}

# Output directories for model scores
OUTPUT_DIRS = {
    "doubao":
    "judge_data/result_v5/result_v5_dyn_var/judge_json/judge_json_v5_dyn_ch/doubao",
    config.MY_MODEL_NAME:
    f"judge_data/result_v5/result_v5_dyn_var/judge_json/judge_json_v5_dyn_ch/{config.MY_MODEL_NAME}",
}

METADATA_DIR = "judge_data/result_v5/result_v5_dyn_var/metadata/metadata_v5_dyn_ch"

client = genai.Client(http_options=types.HttpOptions(base_url=BASE_URL),
                      api_key=API_KEY)


# ---------------------------------------------------------------------
# Utility Functions
# ---------------------------------------------------------------------
def load_prompt_from_jsonl(path, index):
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if i == index:
                obj = json.loads(line)
                return obj["prompt"], obj["dimensions"]
    raise IndexError(f"JSONL line {index} not found")


def list_wavs(folder):
    files = [
        os.path.join(folder, f) for f in os.listdir(folder)
        if f.endswith(".wav")
    ]
    files.sort()
    return files


def load_audio(path):
    """Load audio file, return raw bytes data"""
    with open(path, 'rb') as f:
        audio_bytes = f.read()
    return audio_bytes


def random_assign_T1_T2(base_wav, cand_wav, seed):
    """
    Randomly assign baseline and candidate audio to T1/T2, return:
    1. audio_1, audio_2 (randomly shuffled audio data)
    2. candidate_index (position of candidate audio, 1 or 2)
    
    Use seed to ensure reproducibility.
    """
    rng = random.Random(seed)
    if rng.random() < 0.5:
        # T1 = Candidate, T2 = Baseline. Candidate is at position 1.
        return cand_wav, base_wav, 1
    else:
        # T1 = Baseline, T2 = Candidate. Candidate is at position 2.
        return base_wav, cand_wav, 2


def normalize_json_output(raw_text):
    """
    Clean model raw output text, remove possible ```json prefix and ``` suffix，
    and try to parse as Python dict.
    """
    cleaned_text = raw_text.strip()
    # Remove ```json and ```
    if cleaned_text.startswith("```json"):
        cleaned_text = cleaned_text[len("```json"):].strip()
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-len("```")].strip()

    try:
        # Try to parse JSON
        return json.loads(cleaned_text), "Success"
    except json.JSONDecodeError as e:
        # If parsing fails, return None and error message
        return None, f"JSONDecodeError: {e}"


# ---------------------------------------------------------------------
# Judger Prompt (C.3 version, customized forsingle-round adjustment)
# ---------------------------------------------------------------------
def build_judger_prompts(demand, dims_str):
    system_prompt_judger = (f"""
You are a professional LALM audio generation quality evaluator (Judger). Please strictly and fairly evaluate the provided audio file based on the following scoring criteria.
Your goal is to judge two audios generated by large language models according to user's command and analyze which audio demonstrates superior quality across the paralinguistic feature. 
You will receive an audio file **T1** first, and after my prompt, you will receive the second audio file **T2**.

Both of the user's commands are:"{demand}", and their format is: Please read this sentence with [required paralinguistic features] : '[audio content]'.You need to evaluate whether the audio effectively conveys the required changes of the paralinguistic features.
The text_category for this evaluation is "Dynamic Adjustment": exploring whether LALM can noticeably change paralinguistic features to convey corresponding content in a single audio generation.

### GLOBAL CONSIDERATIONS
- You must strictly adhere to the evaluation criterion and scoring standard below.
- You are acting as a Model-as-a-Judge and should aim to **predict human preference**.
- Your analysis shall be assessed against the requirements specified in {demand} and {dims_str}.
- Your analysis must be grounded in the audio, using **precise timestamps** to justify your findings.
- Resolve borderline cases by articulating fine-grained distinctions (subtle vs. significant) between T1 and T2.
- **If the generated audio is extremely poor or the content is empty, you must assign a score of 0 to that LALM's audio.**

### Anti-Bias Factors:
You must **only** compare the two models based on the **Evaluation Dimensions**. This means you **must not** let the following types of bias influence your judgment:
- The speaker's gender and voice characteristics.
- Any other factor unrelated to the **evaluation_dimension**.
- Models exhibiting exaggerated expressiveness should **not** receive extra reward **unless** those features are relevant to the **evaluation_dimension**.

Evaluation must strictly follow the evaluation_criterion:

### Evaluation Criterion
The goal is to judge whether each large audio language model correctly and naturally express the required audio feature adjustments in single-round generation: {dims_str}.

You must evaluate:
1. **Content Accuracy:** How perfectly the spoken content matches the required text script, without any errors (mispronunciations, omissions, additions, or ambiguous phonetics).
2. **Fluency and Naturalness:** How natural and human-like the pace, pauses, and prosody are, without electronic noise, stutters, or mechanical sounds.
3. **Paralinguistic Compliance - CORE:** Whether the target characteristic/tone/emotion is accurately conveyed in the feature dimension: {dims_str}.
4. If the first two points show no obvious flaws, the focus should be on evaluating **the third CORE point**.

### Detailed Scoring Standard (0–3)

0 = Completely incorrect
    - **Content Accuracy:** Voice content is clearly inconsistent with the script, or the meaning is completely changed due to major errors/omissions. 
    - **Fluency and Naturalness:** Obvious stuttering, discontinuity, strong mechanical electronic tone, completely wrong rhythm, severely impacting listening experience. 
    - **Paralinguistic Compliance - CORE:** The voice completely fails to adjust the specified feature dimensions: {dims_str} within the utterance. The features either remain constant throughout, show a completely wrong direction or timing of change, or produce effects that are opposite to the instructions.

1 = Major issues
    - **Content Accuracy:** Core content is accurate, but there are minor flaws that do not affect understanding (e.g., slight stammering or subtle repetition). 
    - **Fluency and Naturalness:** Overall fluent, but slight inconsistencies in pace, unnatural breathing/pauses, or subtle machine-like sound are noticeable.
    - **Paralinguistic Compliance - CORE:** The attempt to change the feature dimensions: {dims_str} is largely ineffective or unnatural. While the direction of change might be discernible, the magnitude is barely noticeable, or the transition process contains obvious jumps or stutters that break the natural flow.

2 = Partially correct
    - **Content Accuracy:** Voice content is accurate with the script, with only extremely minor, non-distracting mispronunciations or omissions.
    - **Fluency and Naturalness:** The speech is generally very smooth, with only extremely subtle and rare unnatural pauses or rhythmic issues that do not disrupt the overall natural flow.
    - **Paralinguistic Compliance - CORE:** The voice successfully follows the instruction to change the feature dimensions: {dims_str} with the correct direction, but lacks precision. The magnitude of the change may not be obvious enough, the starting or ending states might be slightly inaccurate, or the timing deviates slightly.
    
3 = Fully correct
    - **Content Accuracy:** Voice content is perfectly consistent with the script, with no errors (mispronunciations, omissions, extra words, or ambiguous phonetics).
    - **Fluency and Naturalness:** Pace, pauses, and prosody are indistinguishable from human speech; the sound is natural and fluent, without any electronic noise, stutters, or mechanical feel. 
    - **Paralinguistic Compliance - CORE:** The voice accurately and smoothly changes the feature dimensions: {dims_str} within the utterance. The changes are clear and precise with exact timing according to the instructions, and the transition process is completely natural with no abrupt jumps or stutters.

### Required Reasoning Procedure (Strict)
For each of T1 and T2, you must:

1. Identify which parts of the text prompt require emotional or stylistic expression 
2. Provide **timestamps** for the key expressive segments 
3. Analyze whether the expression matches the intended {dims_str} 
4. Provide a **comparative analysis** highlighting key differences between T1 and T2, annotated as either subtle or significant.
5. Give a final score (0–3) with justification.

### Output Format (Strict JSON)
Your response **must only be a JSON object with the following fields**:

{{
    "reasoning_model_1": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 1.",
    "reasoning_model_2": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 2, **INDEPENDENT** of the performance of model 1.",
    "model_comparison": "str = Keeping in mind the GLOBAL CONSIDERATIONS and the Anti-Bias Factors, compare and contrast the two models based on your output in reasoning_model_1 and reasoning_model_2 and also by analyzing both audios again. Provide very fine-grained reasoning for which model won, or if the comparison results in an even tie.",
    "score_1": "int = Your score for the generated speech from model 1 between 0 and 3, based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2": "int = Your score for the generated speech from model 2 between 0 and 3, based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner": 0 or 1 or 2
}}

Where:
- model_1 = T1
- model_2 = T2
- winner = 
    0  → tie 
    1  → model_1 wins 
    2  → model_2 wins

- Note: Ensure the json structure is followed and the json output **MUST** be parsable without errors.

Now you will be provided with the generated speech from model 1, please analyze it carefully.  **generated_speech_1**
""")
    post_audio_1_message = """ Now you will be provided with the generated speech from the model 2, please analyze it carefully. After that provide the judgment following the ** output_format** ensuring parsability. **generated_speech_2** """
    return system_prompt_judger, post_audio_1_message


# ---------------------------------------------------------------------
# Main Evaluation Process
# ---------------------------------------------------------------------
def evaluate(candidate_name, baseline_name="doubao"):

    os.makedirs(OUTPUT_DIRS[candidate_name], exist_ok=True)

    base_wavs = list_wavs(MODEL_DIRS[baseline_name])
    cand_wavs = list_wavs(MODEL_DIRS[candidate_name])

    if len(base_wavs) != len(cand_wavs):
        raise ValueError("Baseline and candidate audio count mismatch!")

    total = len(base_wavs)

    files_to_process = []
    skipped_count = 0

    for base_path, cand_path in zip(base_wavs, cand_wavs):
        file_name_base = os.path.splitext(os.path.basename(cand_path))[0]
        output_filename = f"{file_name_base}_{candidate_name}_vs_{baseline_name}.json"
        output_path = os.path.join(OUTPUT_DIRS[candidate_name],
                                   output_filename)

        if os.path.exists(output_path):
            skipped_count += 1
        else:
            files_to_process.append((base_path, cand_path))

    if not files_to_process:
        print(f"All files have already been processed! No API calls made.")
        print(f"Total Completed: {total}/{total}")
        return

    print(f"\n[START] Starting run candidate={candidate_name}")
    print(f"Total Files: {total}")
    print(f"Skipped (Already Existed): {skipped_count}")
    print(f"To Process: {len(files_to_process)}")
    print("-" * 60)

    for i, (base_path, cand_path) in enumerate(files_to_process, start=1):

        # Extract sample index from filename (e.g., dyn_var_001 -> 1)
        file_name_base = os.path.splitext(os.path.basename(cand_path))[0]
        sample_index = int(file_name_base.split('_')[-1])

        success = False
        max_retries = 5  # Max retries per sample
        retry_count = 0

        while not success and retry_count < max_retries:
            print(
                f"\n[{candidate_name}] sample {sample_index} started... (attempt {retry_count + 1})"
            )

            try:
                # 1. Load data
                demand, dims = load_prompt_from_jsonl(PROMPT_JSONL, sample_index)
                dims_str = "、".join(dims)
                system_prompt_judger, post_audio_1_message = build_judger_prompts(
                    demand, dims_str)

                base_audio = load_audio(base_path)
                cand_audio = load_audio(cand_path)

                audio_bytes_1, audio_bytes_2, candidate_index = random_assign_T1_T2(
                    base_audio,
                    cand_audio,
                    seed=i +
                    retry_count  # Change seed to prevent model from getting stuck on specific order
                )

                contents = [
                    system_prompt_judger,
                    types.Part.from_bytes(data=audio_bytes_1,
                                          mime_type="audio/wav"),
                    post_audio_1_message,
                    types.Part.from_bytes(data=audio_bytes_2,
                                          mime_type="audio/wav"),
                ]

                # 2. Call API
                response = client.models.generate_content(
                    model=TARGET_MODEL,
                    contents=contents,
                    config=types.GenerateContentConfig(temperature=1.0))

                result_text = response.text

                # 3. Parse JSON
                judger_output_parsed, parse_status = normalize_json_output(
                    result_text)

                if parse_status != "Success":
                    raise ValueError(f"JSON parsing failed: {parse_status}")

                # 4. If we reach here, API and parsing succeeded
                success = True

                # Handle winner mapping
                winner_position = judger_output_parsed.get("winner", 0)

                # 5. Save result
                file_name_base = os.path.splitext(
                    os.path.basename(cand_path))[0]
                output_filename = f"{file_name_base}_{candidate_name}_vs_{baseline_name}.json"

                metadata_data = {
                    "sample_index": sample_index,
                    "candidate_name": candidate_name,
                    "baseline_name": baseline_name,
                    "judger_model": TARGET_MODEL,
                    "demand": demand,
                    "dimensions": dims,
                    "candidate_position": candidate_index,
                    "winner_position": winner_position,
                    "status": "Success",
                    "category": "dynamic_adjustment",
                }

                os.makedirs(METADATA_DIR, exist_ok=True)
                metadata_path = os.path.join(METADATA_DIR, output_filename)
                with open(metadata_path, "w", encoding="utf-8") as f:
                    json.dump(metadata_data, f, ensure_ascii=False, indent=4)
                print(f"[OK] Metadata saved {metadata_path}")

                judger_output_path = os.path.join(OUTPUT_DIRS[candidate_name], output_filename)
                with open(judger_output_path, "w", encoding="utf-8") as f:
                    json.dump(judger_output_parsed, f, ensure_ascii=False, indent=4)
                print(f"[OK] Judger result saved {judger_output_path}")

            except Exception as e:
                retry_count += 1
                print(f"[ERROR] Sample {i} error: {e}")
                if retry_count < max_retries:
                    wait_time = 2**retry_count  # Exponential backoff
                    print(f"Wait {wait_time} seconds before retry...")
                    time.sleep(wait_time)
                else:
                    print(
                        f"[SKIP] Sample {i} failed after {max_retries} retries, skipping。"
                    )

    print("-" * 60)
    print(f"Done! Overall Success (including skipped): {total}/{total}")
    print(f"Skipped (Already Existed): {skipped_count}")
    print(f"Actually Processed this run: {len(files_to_process)}")


# ---------------------------------------------------------------------
# Main Entry
# ---------------------------------------------------------------------
if __name__ == "__main__":
    evaluate(config.MY_MODEL_NAME, baseline_name="doubao")
    print("\nAll tasks completed！")
