import os
import json
import random
from tracemalloc import start
import soundfile as sf
import numpy as np

from google import genai
from google.genai import types

# ---------------------------------------------------------------------
#  基础配置
# ---------------------------------------------------------------------
YOUR_API_KEY = ""
BASE_URL = "http://43.131.235.107:45101/"
TARGET_MODEL = "gemini-3-pro-preview"

PROMPT_JSONL = "jsonl_prompt_en/para_con/long_sin.jsonl"

# 已生成的音频目录
MODEL_DIRS = {
    # "doubao": "api_models/doubao/output_en/para_con/con_long_sin",
    # "gpt": "api_models/gpt/output_en/para_con/con_long_sin",
    "gemini": "api_models/gemini/output_en/para_con/con_long_sin",
    # "qwen-omni": "api_models/qwen-omni/output_en/para_con/con_long_sin",
    # "qwen-omni-realtime": "api_models/qwen-omni-realtime/output_en/para_con/con_long_sin",
    "YOU_MODEL_NAME": "api_models/YOU_MODEL/output_en/para_con/con_long_sin",
}

# 输出各模型的评分 jsonl
OUTPUT_DIRS = {
    "gemini":
    "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/gemini",
    # "gpt": "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/gpt",
    # "doubao": "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/doubao",
    # "qwen-omni": "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/qwen-omni",
    # "qwen-omni-realtime": "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/qwen-omni-realtime",
    "YOU_MODEL_NAME":
    "judge_data/result_v5/result_v5_para_con/judge_json/judge_json_v5_long_sin_en/YOU_MODEL_NAME",
}

METADATA_DIR = "评测数据/测试v5_para_con/metadata/metadata_v5_long_sin_en"

client = genai.Client(http_options=types.HttpOptions(base_url=BASE_URL),
                      api_key=YOUR_API_KEY)


# ---------------------------------------------------------------------
# 工具函数
# ---------------------------------------------------------------------
def load_prompt_from_jsonl(path, index):
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if i == index:
                obj = json.loads(line)
                return obj["prompt"], obj["dimensions"]
    raise IndexError(f"JSONL 不足 {index} 行")


def list_wavs(folder):
    files = [
        os.path.join(folder, f) for f in os.listdir(folder)
        if f.endswith(".wav")
    ]
    files.sort()
    return files


def load_audio(path):
    """加载音频文件，返回原始字节数据 (bytes)"""
    with open(path, 'rb') as f:
        audio_bytes = f.read()
    return audio_bytes


def random_assign_T1_T2(base_wav, cand_wav, seed):
    """
    随机分配基线和候选音频到 T1/T2，并返回：
    1. audio_1, audio_2 (已随机排序的音频数据)
    2. candidate_index (候选音频所在的位置, 1 或 2)
    
    使用 seed 确保随机分配的可复现性。
    """
    rng = random.Random(seed)
    if rng.random() < 0.5:
        # T1 = Candidate, T2 = Baseline. Candidate is at position 1.
        return cand_wav, base_wav, 1
    else:
        # T1 = Baseline, T2 = Candidate. Candidate is at position 2.
        return base_wav, cand_wav, 2


def normalize_json_output(raw_text):
    """
    清理模型的原始输出文本，去除可能的 ```json 前缀和 ``` 后缀，
    并尝试解析为 Python 字典。
    """
    cleaned_text = raw_text.strip()
    # 移除 ```json 和 ```
    if cleaned_text.startswith("```json"):
        cleaned_text = cleaned_text[len("```json"):].strip()
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-len("```")].strip()

    try:
        # 尝试解析 JSON
        return json.loads(cleaned_text), "Success"
    except json.JSONDecodeError as e:
        # 如果解析失败，返回 None 和错误信息
        return None, f"JSONDecodeError: {e}"


# ---------------------------------------------------------------------
# Judger Prompt (C.3版本，定制为para_con)
# ---------------------------------------------------------------------
def build_judger_prompts(demand, dims_str, dims):
    system_prompt_judger = (f"""
You are a professional LALM audio generation quality evaluator (Judger). Please strictly and fairly evaluate the provided audio file based on the following scoring criteria.
Your goal is to judge two audios generated by large language models according to user's command and analyze which audio demonstrates superior quality across the paralinguistic feature. 
You will receive an audio file **T1** first, and after my prompt, you will receive the second audio file **T2**.

Both of the user's commands are:"{demand}", and their format is: Please read this sentence with [required paralinguistic features] : '[audio content]'.You need to evaluate whether the audio effectively conveys the required paralinguistic dimensions.
The text_category for this evaluation is "Feature Control": exploring whether LALM can accurately generate audio following user's command "{demand}", with specified features "{dims_str}".

### GLOBAL CONSIDERATIONS
- You must strictly adhere to the evaluation criterion and scoring standard below.
- You are acting as a Model-as-a-Judge and should aim to **predict human preference**.
- Your analysis shall be assessed against the requirements specified in {demand} and {dims_str}.
- Your analysis must be grounded in the audio, using **precise timestamps** to justify your findings.
- Resolve borderline cases by articulating fine-grained distinctions (subtle vs. significant) between T1 and T2.
- **If the generated audio is extremely poor or the content is empty, you must assign a score of 0 to that LALM's audio.**

### Anti-Bias Factors:
You must **only** compare the two models based on the **Evaluation Dimensions**. This means you **must not** let the following types of bias influence your judgment:
- The speaker's gender and voice characteristics.
- Any other factor unrelated to the **evaluation_dimension**.
- Evaluations for each paralinguistic dimension must be **INDEPENDENT OF ONE ANOTHER**, which means judgments regarding the performance of the current dimension should not be influenced by the performance of other dimensions.
- Models exhibiting exaggerated expressiveness should **not** receive extra reward **unless** those features are relevant to the **evaluation_dimension**.

Evaluation must strictly follow the evaluation_criterion:

### Evaluation Criterion
The goal is to judge whether each large audio language model correctly and naturally expresses the required controllable characteristic(s): {dims_str}.

You must evaluate or follow:
1. **Content Accuracy:** How perfectly the spoken content matches the required text script, without any errors (mispronunciations, omissions, additions, or ambiguous phonetics).
2. **Fluency and Naturalness:** How natural and human-like the pace, pauses, and prosody are, without electronic noise, stutters, or mechanical sounds.
3. **Paralinguistic Compliance - CORE:** Whether the target characteristic/tone/emotion(s) in the feature dimension: {dims_str} is(are) accurately conveyed.
4. If {dims_str} contains multiple dimensions, please assign a **separate score** to each dimension.
5. If the first two points show no obvious flaws, the focus should be on evaluating **the third CORE point**.

### Detailed Scoring Standard (0–3)

0 = Completely incorrect
    - **Content Accuracy:** Voice content is clearly inconsistent with the script, or the meaning is completely changed due to major errors/omissions. 
    - **Fluency and Naturalness:** Obvious stuttering, discontinuity, strong mechanical electronic tone, completely wrong rhythm, severely impacting listening experience. 
    - **Paralinguistic Compliance - CORE:** Flat tone, completely devoid of emotion/features, or even expressing the opposite characteristic/tone. 

1 = Major issues
    - **Content Accuracy:** Core content is accurate, but there are minor flaws that do not affect understanding (e.g., slight stammering or subtle repetition). 
    - **Fluency and Naturalness:** Overall fluent, but slight inconsistencies in pace, unnatural breathing/pauses, or subtle machine-like sound are noticeable.
    - **Paralinguistic Compliance - CORE:** Characteristic change is present but emotion is insufficiently or unclearly expressed; the target feature can only be vaguely perceived, or the expression seems stiff.

2 = Partially correct
    - **Content Accuracy:** Voice content is accurate with the script, with only extremely minor, non-distracting mispronunciations or omissions.
    - **Fluency and Naturalness:** The speech is generally very smooth, with only extremely subtle and rare unnatural pauses or rhythmic issues that do not disrupt the overall natural flow.
    - **Paralinguistic Compliance - CORE:** The characteristic or emotion is correctly expressed and clearly discernible, but the intensity or consistency is slightly lacking in certain segments, preventing it from being perfectly "vivid and spot-on."
    
3 = Fully correct
    - **Content Accuracy:** Voice content is perfectly consistent with the script, with no errors (mispronunciations, omissions, extra words, or ambiguous phonetics).
    - **Fluency and Naturalness:** Pace, pauses, and prosody are indistinguishable from human speech; the sound is natural and fluent, without any electronic noise, stutters, or mechanical feel. 
    - **Paralinguistic Compliance - CORE:** Sound features clearly and accurately embody the target characteristic; emotional expression is vivid and spot-on (the 'anchor'), and the listener can immediately perceive the emotion. 

### Required Reasoning Procedure (Strict)
For each of T1 and T2, you must:

1. Identify which parts of the text prompt require emotional or stylistic expression 
2. Provide **timestamps** for the key expressive segments 
3. Analyze whether the expression matches the intended {dims_str} 
4. For each dimension of {dims_str}, provide a **comparative analysis** highlighting key differences between T1 and T2, annotated as either subtle or significant.
5. For each dimension of {dims_str}, give a final score (0–3) with justification.
6. The evaluation of each dimension in {dims_str} should be **mutually independent**.

### Output Format (Strict JSON)
Your response **must only be a JSON object with the following fields** (assuming {dims} contains n dimensions):

{{
    "reasoning_model_1": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 1.",
    "reasoning_model_2": "str = Reasoning chain based on the Required Reasoning Procedure for the generated speech from model 2, **INDEPENDENT** of the performance of model 1.",
    "model_comparison": "str = Keeping in mind the GLOBAL CONSIDERATIONS and the Anti-Bias Factors, compare and contrast the performance of the two models across {dims_str} based on your output in reasoning_model_1 and reasoning_model_2 and also by analyzing both audios again. Provide very fine-grained reasoning for which model won, or if the comparison results in an even tie.",
    "score_1_1": "int = Score (0–3) for model 1 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_1": "int = Score (0–3) for model 2 on dimension dims[0], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_1": 0 or 1 or 2
    "score_1_2": "int = Score (0–3) for model 1 on dimension dims[1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_2": "int = Score (0–3) for model 2 on dimension dims[1]., based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_2": 0 or 1 or 2
    ……
    "score_1_n": "int = Score (0–3) for model 1 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_1.",
    "score_2_n": "int = Score (0–3) for model 2 on dimension dims[n-1], based on the evaluation_criterion and what you have mentioned in reasoning_model_2.",
    "winner_n": 0 or 1 or 2
}}

Where:
- model_1 = T1
- model_2 = T2
- winner_n = 
    0  → tie 
    1  → model_1 wins 
    2  → model_2 wins

- Note: Ensure the json structure is followed and the json output **MUST** be parsable without errors.

Now you will be provided with the generated speech from model 1, please analyze it carefully.  **generated_speech_1**
""")
    post_audio_1_message = """ Now you will be provided with the generated speech from the model 2, please analyze it carefully. After that provide the judgment following the ** output_format** ensuring parsability. **generated_speech_2** """
    return system_prompt_judger, post_audio_1_message


# ---------------------------------------------------------------------
# 主评测流程
# ---------------------------------------------------------------------
def evaluate(candidate_name, baseline_name="gemini", start_index=1):

    os.makedirs(OUTPUT_DIRS[candidate_name], exist_ok=True)

    # 按 index 读取音频
    base_wavs = list_wavs(MODEL_DIRS[baseline_name])
    cand_wavs = list_wavs(MODEL_DIRS[candidate_name])

    if len(base_wavs) != len(cand_wavs):
        raise ValueError("基线和候选模型音频数量不一致！")

    total = len(base_wavs)

    # ---- 新增：从 start_index 起切片 ----
    base_wavs = base_wavs[start_index - 1:]
    cand_wavs = cand_wavs[start_index - 1:]

    # ---- enumerate 起始编号也设为 start_index ----
    for i, (base_path, cand_path) in enumerate(zip(base_wavs, cand_wavs),
                                               start=start_index):

        print(f"\n[{candidate_name}] 样本 {i} 开始处理...")

        result_text = ""
        status = "Error"
        candidate_index = -1  # 默认值，以防异常

        try:
            # 读取 prompt
            demand, dims = load_prompt_from_jsonl(PROMPT_JSONL, i)
            dims_str = "、".join(dims)

            # 构建 Judger prompt (获取 System, User, Post-Audio 1 消息)
            system_prompt_judger, post_audio_1_message = build_judger_prompts(
                demand, dims_str, dims)

            # -------------------------------
            # 读取音频 + 随机分配 T1 / T2
            # -------------------------------
            base_audio = load_audio(base_path)
            cand_audio = load_audio(cand_path)

            # 使用样本索引 i 作为种子，确保可复现性
            audio_bytes_1, audio_bytes_2, candidate_index = random_assign_T1_T2(
                base_audio, cand_audio, seed=i)
            # -------------------------------
            # 构造多模态 Contents 列表 (交错文本和音频)
            # -------------------------------
            contents = [
                system_prompt_judger,
                types.Part.from_bytes(data=audio_bytes_1,
                                      mime_type="audio/wav"),
                post_audio_1_message,
                types.Part.from_bytes(data=audio_bytes_2,
                                      mime_type="audio/wav"),
            ]

            # -------------------------------
            # 调用 Gemini 评分
            # -------------------------------
            config = types.GenerateContentConfig(
                temperature=1.0,  # gemini 3 pro 最好保持1.0
                # temperature=0.0,
            )

            # 实际的 API 调用
            response = client.models.generate_content(model=TARGET_MODEL,
                                                      contents=contents,
                                                      config=config)

            result_text = response.text
            status = "Success"

        except Exception as e:
            print(f"❌ 样本 {i} 调用 API 或处理时发生错误: {str(e)}")
            # 构建一个包含错误的 JSON 字符串作为模型的输出
            result_text = json.dumps(
                {
                    "reasoning_system_1": f"Client/Processing Error: {str(e)}",
                    "reasoning_system_2": f"Client/Processing Error: {str(e)}",
                    "model_comparison": f"Client/Processing Error: {str(e)}",
                    "score_1": -1,
                    "score_2": -1,
                    "winner": -1
                },
                ensure_ascii=False)

        # -------------------------------
        # 处理并解析 Judger 输出
        # -------------------------------
        judger_output_parsed, parse_status = normalize_json_output(result_text)

        winner_positions = {}

        if parse_status.startswith("JSONDecodeError"):
            status = "JSON_Parse_Error"
            # 如果解析失败，确保 judger_output_parsed 包含错误信息
            judger_output_parsed = {
                "error": parse_status,
                "winner": -1,
                "score_1": -1,
                "score_2": -1
            }
            winner_position = -1
        elif status == "Success":
            # 如果 API 调用成功，且 JSON 解析成功，则进一步获取 winner_position
            for idx in range(1, len(dims) + 1):
                key = f"winner_{idx}"
                winner_positions[
                    f"winner_position_{idx}"] = judger_output_parsed.get(
                        key, -1)

        # ---- 文件名生成：使用候选音频的文件名作为基础名 ----
        file_name_base = os.path.splitext(os.path.basename(cand_path))[0]
        # 文件名保持一致，便于关联
        output_filename = f"{file_name_base}_{candidate_name}_vs_{baseline_name}.json"

        # -------------------------------
        # 保存输出 jsonl
        # -------------------------------
        metadata_data = {
            "sample_index": i,
            "candidate_name": candidate_name,
            "baseline_name": baseline_name,
            "judger_model": TARGET_MODEL,
            "demand": demand,
            "dimensions": dims,
            "candidate_position": candidate_index,  # 候选音频所在位置 (1 或 2)
            "status": status,
            "category": "feature_control",
        }
        # ---- 新增：逐维度 winner_position ----
        for idx in range(1, len(dims) + 1):
            key = f"winner_position_{idx}"
            metadata_data[key] = winner_positions.get(key, -1)

        # 使用候选音频的文件名作为输出文件的基础名，并添加 '_comparison.jsonl' 后缀
        metadata_path = os.path.join(METADATA_DIR, output_filename)
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata_data, f, ensure_ascii=False, indent=4)
        print(f"✔ 元数据已保存 {metadata_path}")

        judger_output_path = os.path.join(OUTPUT_DIRS[candidate_name],
                                          output_filename)
        with open(judger_output_path, "w", encoding="utf-8") as f:
            json.dump(judger_output_parsed, f, ensure_ascii=False, indent=4)
        print(f"✔ 评判结果已保存 {judger_output_path}")

    print(f"\n任务完成，处理范围：[{start_index} ~ {total}]")


def run_with_auto_resume(candidate_name,
                         baseline_name="gemini",
                         start_index=1):
    """
    自动监视 evaluate()，若 evaluate 中断（异常/崩溃/退出），
    则自动从下一个样本 start_index 继续进行。
    """

    while True:
        try:
            print(
                f"\n🚀 开始运行 candidate={candidate_name}, 从 start_index={start_index}"
            )

            # ----------------------------
            # 核心：调用你的 evaluate()
            # ----------------------------
            evaluate(candidate_name, baseline_name, start_index=start_index)

            # 能运行到这里 → evaluate 正常结束，说明任务成功
            print(f"\n🎉 {candidate_name} 全部正常结束！评测完成。")
            break

        except Exception as e:
            # 捕获 evaluate 内没捕获到的所有异常（例如断电/脚本退出等）
            print(f"\n❌ evaluate() 发生未捕获异常：{e}")
            print("⚠️ 自动查找已完成的最后一个样本，继续向后评测…")

            # -----------------------------------------------------------
            # 自动更新 start_index：扫描 output 目录下已生成的 json 文件数量
            # -----------------------------------------------------------

            output_dir = OUTPUT_DIRS[candidate_name]
            finished = [
                f for f in os.listdir(output_dir)
                if f.endswith(".json") or f.endswith(".jsonl")
            ]
            # 已完成样本的数量 + 1 = 下一个 start_index
            new_start = len(finished) + 1

            print(
                f"👉 已完成 {len(finished)} 个样本，下一次将从 start_index={new_start} 继续")

            # 更新 start_index 并继续 while True
            start_index = new_start


# ---------------------------------------------------------------------
# 主入口
# ---------------------------------------------------------------------
# if __name__ == "__main__":
#     evaluate("gpt4o")
#     evaluate("gemini")
#     evaluate("qwen-omni")
#     print("\n全部任务完成！")
if __name__ == "__main__":
    # run_with_auto_resume("gpt", start_index=1)
    # run_with_auto_resume("doubao", start_index=1)
    # run_with_auto_resume("qwen-omni", start_index=1)
    run_with_auto_resume("YOU_MODEL_NAME", start_index=1)
    print("\n全部任务完成！")
